# Generated by Django 5.0 on 2023-12-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_invoice_supplier_invoiceitem_invoice_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availibility',
            new_name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
