# Generated by Django 5.0 on 2023-12-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
